title: LIANG
description: A man like girls🫡.
author: LIANG Guangyi
avatar: /logo_new.png
email: liangguangyi@mail.ustc.edu.cn
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

subscribe: false

skin: sunrise

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Liang Guangyi
  card: summary
logo: logo_new.png
social:
  name: Liang Guangyi
  links:
    - https://github.com/liangguangyii
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
